# Generated by Django 5.2.4 on 2025-07-28 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('publishing_year', models.PositiveIntegerField()),
                ('count_available', models.PositiveIntegerField()),
                ('format', models.CharField(choices=[('Physical', 'Physical'), ('eBook', 'eBook'), ('AudioBook', 'AudioBook')], default='Physical', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('rating', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='userRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('loginID', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'userRegister',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('booknames', models.CharField(max_length=300)),
                ('bookids', models.CharField(max_length=200)),
                ('quantities', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(choices=[('Card', 'Card'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking'), ('COD', 'Cash on Delivery')], max_length=30)),
                ('card_details', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed')], max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_number', models.CharField(max_length=100, unique=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userregistrationmodel')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bookid', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.bookmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userregistrationmodel')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
