# Generated by Django 5.2.4 on 2025-07-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
