# Generated by Django 5.2.4 on 2025-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userregistrationmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='loginID',
            field=models.IntegerField(),
        ),
    ]
